# Generated by Django 3.1.2 on 2020-10-07 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Biografia', models.CharField(max_length=1000)),
                ('Genero', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('Idioma', models.CharField(max_length=8)),
                ('Fecha_Publicacion', models.DateField(null=True)),
                ('Resumen', models.CharField(max_length=1000)),
                ('Precio', models.PositiveIntegerField(default=0)),
                ('Autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero para este libro', to='catalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('ids', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('disponibilidad_libro', models.CharField(blank=True, default='En stock', help_text='Disponibilidad del libro', max_length=20)),
                ('numero_unidades', models.PositiveIntegerField(default=0)),
                ('libro_disponibles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.libro')),
            ],
        ),
    ]
