# Generated by Django 3.1.2 on 2020-10-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201007_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(blank=True, choices=[('s', 'En Stock'), ('a', 'Agotado')], default='s', help_text='Disponibilidad del libro', max_length=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.BigIntegerField(),
        ),
    ]
