# Generated by Django 3.1.2 on 2020-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201009_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='disponibilidad_libro',
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.BigIntegerField(unique=True),
        ),
    ]
