# Generated by Django 3.1.2 on 2020-10-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201013_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=13),
        ),
    ]
